#!/usr/bin/env python3
"""
set_dashboard_update.py
───────────────────────────────────────────────────────────────────────────────
Re-bakes PORT, SIGNALS, REGIME, and REMOTE_HISTORY constants into
set_dashboard.html so the page shows correct data even before auto-sync fires.

Run this after set_eod_report.py or set_realtime_monitor.py to keep the
embedded data in sync with the JSON files.

Usage:
    python3 set_dashboard_update.py
"""

import json, re, os, datetime, sys

SCRIPT_DIR     = os.path.dirname(os.path.abspath(__file__))
PORTFOLIO_PATH = os.path.join(SCRIPT_DIR, "set_portfolio.json")
SIGNALS_PATH   = os.path.join(SCRIPT_DIR, "set_signal_state.json")
HISTORY_PATH   = os.path.join(SCRIPT_DIR, "set_history.json")
DASHBOARD_PATH = os.path.join(SCRIPT_DIR, "set_dashboard.html")

# ── Load JSON files ────────────────────────────────────────────────────────────
def load_json(path, fallback):
    if not os.path.exists(path):
        print(f"  ⚠️  Missing: {path} — using fallback")
        return fallback
    with open(path, encoding="utf-8") as f:
        return json.load(f)

port    = load_json(PORTFOLIO_PATH, {})
signals = load_json(SIGNALS_PATH,   {})
history = load_json(HISTORY_PATH,   [])

# Extract regime block from signal state
regime  = signals.get("_regime", {})

if not port:
    print("❌  No portfolio data found. Aborting.")
    sys.exit(1)

# ── Read current HTML ──────────────────────────────────────────────────────────
with open(DASHBOARD_PATH, encoding="utf-8") as f:
    html = f.read()

# ── Build replacement strings (compact JSON, no extra whitespace) ──────────────
port_json    = json.dumps(port,    ensure_ascii=False, separators=(',', ':'))
signals_json = json.dumps(signals, ensure_ascii=False, separators=(',', ':'))
history_json = json.dumps(history, ensure_ascii=False, separators=(',', ':'))
regime_json  = json.dumps(regime,  ensure_ascii=False, separators=(',', ':'))

now_bkk = datetime.datetime.utcnow() + datetime.timedelta(hours=7)
ts = now_bkk.strftime("%Y-%m-%d %H:%M")

# ── Replace PORT constant ──────────────────────────────────────────────────────
port_pattern = re.compile(
    r'(const PORT\s*=\s*)(\{.*?\})(;)',
    re.DOTALL
)
if not port_pattern.search(html):
    print("❌  Could not find 'const PORT = ...' in dashboard HTML. Aborting.")
    sys.exit(1)
html = port_pattern.sub(rf'\g<1>{port_json}\g<3>', html)

# ── Replace SIGNALS constant ───────────────────────────────────────────────────
sig_pattern = re.compile(
    r'(const SIGNALS\s*=\s*)(\{.*?\})(;)',
    re.DOTALL
)
if sig_pattern.search(html):
    html = sig_pattern.sub(rf'\g<1>{signals_json}\g<3>', html)
else:
    print("  ⚠️  Could not find 'const SIGNALS = ...' — skipping signals update")

# ── Replace REGIME constant ───────────────────────────────────────────────────
reg_pattern = re.compile(
    r'(const REGIME\s*=\s*)(\{.*?\})(;)',
    re.DOTALL
)
if reg_pattern.search(html):
    html = reg_pattern.sub(rf'\g<1>{regime_json}\g<3>', html)
    if regime:
        print(f"  📡 Regime: {regime.get('regime','?')}  "
              f"SET {regime.get('set_px','?')}  MA200 {regime.get('ma200','?')}  "
              f"({regime.get('updated','?')})")
    else:
        print("  ⚠️  Regime block empty — monitor hasn't run yet today")
else:
    print("  ⚠️  Could not find 'const REGIME = ...' — skipping regime update")

# ── Replace REMOTE_HISTORY ─────────────────────────────────────────────────────
hist_pattern = re.compile(
    r'(let REMOTE_HISTORY\s*=\s*)(\[.*?\])(;.*?//.*?$)',
    re.DOTALL | re.MULTILINE
)
if hist_pattern.search(html):
    html = hist_pattern.sub(
        rf'\g<1>{history_json}; // pre-baked; refreshed from GitHub on sync',
        html
    )
else:
    print("  ⚠️  Could not find 'let REMOTE_HISTORY = ...' — skipping history update")

# ── Update timestamp comment ───────────────────────────────────────────────────
ts_pattern = re.compile(
    r'(// Updated:)[^\n]+'
)
if ts_pattern.search(html):
    html = ts_pattern.sub(
        f'// Updated: {ts} Bangkok · regenerated by set_dashboard_update.py',
        html
    )

# ── Bake DASHBOARD_UPDATED constant (shown in top bar with age colouring) ─────
du_pattern = re.compile(r'(const DASHBOARD_UPDATED\s*=\s*")[^"]*(")')
if du_pattern.search(html):
    html = du_pattern.sub(rf'\g<1>{ts} Bangkok\g<2>', html)

# ── Write updated HTML ────────────────────────────────────────────────────────
with open(DASHBOARD_PATH, "w", encoding="utf-8") as f:
    f.write(html)

day  = port.get('day_count', '?')
val  = port.get('cash', 0) + sum(
    h['shares'] * h.get('last_price', h['avg_cost'])
    for h in port.get('holdings', {}).values()
)
reg_str = regime.get('regime', 'unknown') if regime else 'unknown'
print(f"✅  Dashboard updated  —  Day {day}  |  Value ฿{val:,.0f}  |  Regime {reg_str}  |  {len(history)} history entries  |  {ts} BKK")
